# Generated by Django 5.2.6 on 2025-12-11 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={'permissions': (('Ver_prestamo', 'Puede ver el prestamo'), ('gestionar_prestamos', 'Puede gestionar prestamos'))},
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='Autor',
            new_name='autor',
        ),
    ]
