# Generated by Django 5.2.9 on 2026-01-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_libro_anio_libro_descripcion_libro_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
