# Generated by Django 5.2.9 on 2026-01-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_libro_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='anio',
        ),
        migrations.AddField(
            model_name='libro',
            name='anio_publicacion',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
