# Generated by Django 5.2.9 on 2026-01-03 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_remove_libro_anio_libro_anio_publicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='fecha_prestamos',
            new_name='fecha_prestamo',
        ),
    ]
