# Generated by Django 5.2.9 on 2026-01-03 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_rename_fecha_prestamos_prestamo_fecha_prestamo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='fecha_prestamo',
            new_name='fecha_prestamos',
        ),
    ]
