# Generated by Django 5.2.9 on 2026-01-05 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_rename_fecha_prestamo_prestamo_fecha_prestamos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='genero',
        ),
    ]
