# Generated by Django 5.2.9 on 2026-01-07 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_libro_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multa',
            options={'permissions': [('pagar_multa', 'Puede registrar el pago de una multa')]},
        ),
        migrations.AlterModelOptions(
            name='prestamo',
            options={'permissions': [('gestionar_prestamo', 'Puede aprobar o denegar préstamos'), ('Ver_prestamo', 'Puede ver la lista detallada de préstamos')]},
        ),
    ]
